version: 0.2

run-as: Linux-user-name
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    run-as: Linux-user-name
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-north-1)
  build:
    run-as: Linux-user-name
    commands:
      - docker build -t ib92/awscodesuite:1.0 .