version: 0.2

run-as: Linux-user-name

env:
  git-credential-helper: yes

proxy:
    upload-artifacts: yes
    logs: yes
            
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - docker-compose build
      - docker-compose down
      - docker-compose run --rm sae-application -c ./scripts/run-all-tests.sh
  post_build:
    commands:
      - docker-compose run --rm --no-deps sae-application -c './scripts/run-init-environment.sh && serverless package'
      - docker-compose down
