version: 0.2           
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - BUILD_START_TIMESTAMP=date +%s
      - docker-compose build
  post_build:
    commands:
      - docker-compose run --rm awscodesuite-application -c ./scripts/run-all-tests.sh
      - docker-compose run --rm --no-deps awscodesuite-application -c 'serverless package'
      - size=$(stat --printf='%s' .serverless/awscodesuite.zip)
      - aws cloudwatch put-metric-data --namespace KPM --metric-name PR_package_size --unit Bytes --value $(size)
      - docker-compose down
