version: 0.2           
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo "foo bar"
      - docker-compose build
      - docker-compose down
  post_build:
    commands:
      - docker-compose run --rm awscodesuite-application -c ./scripts/run-all-tests.sh
      - docker-compose run --rm --no-deps awscodesuite-application -c 'serverless package'
      - docker-compose down
